# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Domingo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Domingo
  pod 'Firebase/Messaging'

  target 'Domingo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  end

  target 'DomingoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
